instance of OsConfigResource as $OsConfigResource0ref {
   ResourceID = "Ensure nosuid option set on /tmp partition";
   PayloadKey = "/cis/Ubuntu/22.04/v2.0.0/1/1/2/1/3";
   RuleId = "a87f15ed-1115-a22d-6f43-17db97c91191";
   ComponentName = "Compliance";
   InitObjectName = "e30K";
   ReportedObjectName = "eyJhbnlPZiI6W3sibm90Ijp7InBhY2thZ2VJbnN0YWxsZWQiOnsicGFja2FnZU5hbWUiOiIkQ1JPTl9QS0dfTkFNRSJ9fX0seyJlbnN1cmVGaWxlUGVybWlzc2lvbnMiOnsiZmlsZW5hbWUiOiIvZXRjL2Nyb250YWIiLCJ1c2VyIjoicm9vdCIsImdyb3VwIjoicm9vdCIsInBlcm1pc3Npb25zIjoiNjAwIn19XX0K";
   ExpectedObjectValue = "PASS";
   DesiredObjectName = "eyJhbnlPZiI6W3sibm90Ijp7InBhY2thZ2VJbnN0YWxsZWQiOnsicGFja2FnZU5hbWUiOiIkQ1JPTl9QS0dfTkFNRSJ9fX0seyJlbnN1cmVGaWxlUGVybWlzc2lvbnMiOnsiZmlsZW5hbWUiOiIvZXRjL2Nyb250YWIiLCJ1c2VyIjoicm9vdCIsImdyb3VwIjoicm9vdCIsInBlcm1pc3Npb25zIjoiNjAwIn19XX0K";
   DesiredObjectValue = "CRON_PKG_NAME=cron";
   ModuleName = "GuestConfiguration";
   ModuleVersion = "1.0.0";
   ConfigurationName = "Compliance";
   SourceInfo = "::4::5::OsConfigResource";
};

instance of OMI_ConfigurationDocument
{
    Version="3.0.0";
    CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};
    Author="Microsoft";
    GenerationDate="1/22/2025 14:54:00 PST";
    Name="ComplianceExample";
};
